### ISSUE TITLE
OOM errors on large images

### ISSUE THREAD

**Issue by CrispyBaguette** [CrispyBaguette/wasm-palette-converter#2]
![image](https://user-images.githubusercontent.com/11209123/143130979-bc161b17-d6f8-40bd-9798-b3beb8319a37.png)
Switch to in-place dither ? Find out how to increase available memory ? Both ?

**Comment by tfuxu** [comment]
Try updating to [dither v2.4.0](https://github.com/makew0rld/dither/releases/tag/v2.4.0), as it fixes several memory issues in the library.
